package misc;

import java.io.BufferedReader;
import java.io.InputStreamReader;

/**The Variables class contain some public vars that are used all over the program*/
public class Variables {

    /** General var to hold user input*/
    public static String input;

    /**Index [column number] [type, order in it's type]
     *<br> type: 0 = String, 1 = Integer*/
    public static int [][] index = new int [1000][2];

    /** strArr [column] [row] <br> column = order in it's type*/
    public static String[][] strArr = new String [1000] [1000];
    public static int[][] intArr = new int [1000] [1000];

    /** Variables to keep track of the number of columns & rows */
    public static int noOfColumns = 0, noOfRows = 0;

    /** Variables to keep track the Names of columns & rows */
    public static String[] columnNames = new String [1000];

    /**Declaring a buffered reader to read user input from the console*/
    public static BufferedReader consRead = new BufferedReader (new InputStreamReader(System.in));

    /**Array to hold the maximum column width values that will be generated by
     *(setColumnWidth) method, then these values will be called when printing to format the output*/
    public static int[] columnWidth = new int [1000];





}
